### ISSUE TITLE
20.04.1 with kernel 5.8: brightness not persistent

### ISSUE THREAD

**Issue by zilexa** [jrandiny/yoga-slim7-ubuntu#1]
I have a Lenovo S540 13-ARE, similar to the Slim7 but with a 16:10 screen and 4800U. 
After updating kernel to 5.8, everything works, even suspend (hibernation does not work but I suppose that requires some software tweaking). 

The only issue: brightness setting is not persistent after a reboot:
the screen is very bright after reboot, but as soon as I hit the quick button on my keyboard to reduce brightness, it starts at almost the lowest settting and the brightness is dimmed immediately to its (almost) lowest.

I read here, the Slim 7 has the same issue: https://forums.lenovo.com/t5/Ubuntu/Lenovo-Ideapad-Slim-7-AMD-Ryzen-7-4700U-suspend-resume-issues/m-p/5019372?page=3#5119584

Do you know how to fix this or how to at least set a lower default value, to not get blinded after a reboot?

**Comment by jrandiny** [comment]
Hmmm on my system i haven't seen this problem (slim 7, 4800u, kernel 5.8.2). However maybe you can try running the following script on startup
```
```

**Comment by zilexa** [comment]
When I cat that file `cat /sys/class/backlight/amdgpu_bl0/brightness` it says `14`.
This matches the setting it is on after reboot: the screen is very bright but as soon as I hit the - button, it goes dark immediately, meaning it starts at 14 as soon as I change brightness. 

I tried setting it to 5 and also to 50. No change. Max brightness at boot.

**Comment by zilexa** [comment]
I am going to try kernel 5.8.2 instead of 5.8. Did you get 5.8.2 from the mainline repository?
Because as I understand only 5.8 is official..

**Comment by jrandiny** [comment]
Yes i use the mainline repository, the officially supported kernel right now for Ubuntu 20.04 is Linux 5.4

**Comment by rjd22** [comment]
@zilexa I had this same issue and found out for me it was the auto brightness setting in the ubuntu config that was messing with me. Other issues I had was that the brightness was constantly fluctuating.

**Comment by jrandiny** [comment]
Closed for inactivity
