### ISSUE TITLE
Problems recompiling ACPI override

### ISSUE THREAD

**Issue by jkflying** [jrandiny/yoga-slim7-ubuntu#11]
After applying the patch (which didn't apply cleanly, all those errors at the top aren't there on my system), I couldn't re-compile the firmware due to compiler errors referring to AFN7:
```
root@Condor:~/acpica-unix-20200717/acpi# iasl -ve -tc dsdt.dsl

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200717
Copyright (c) 2000 - 2020 Intel Corporation

dsdt.dsl   3076:                             AFN7 (Local0)
Error    6086 -                                ^ Not a control method, cannot invoke (AFN7 is a Untyped)

ASL Input:     dsdt.dsl -  512781 bytes   5576 keywords  15026 source lines
Hex Dump:      dsdt.hex -  554189 bytes

Compilation failed. 1 Errors, 59 Warnings, 198 Remarks
No AML files were generated due to compiler error(s)
```

Searching dsdt.dsl, AFN7 appears on line 29:
`    External (_SB_.PCI0.GP17.VGA_.AFN7, UnknownObj)`
line 59:
`    External (AFN7, MethodObj)    // 1 Arguments`
And on the line that gives the errors:
```
                        Method (_BCM, 1, NotSerialized)  // _BCM: Brightness Control Method
                        {
                            Divide ((Arg0 * 0xFF), 0x64, Local1, Local0)
                            AFN7 (Local0)
                            BRTL = Arg0
                        }
```

I tried deleting all references to AFN7 and it compiles and the S3 is working at least. Any idea what I've broken by doing this? Based on where it it used I'd guess something to do with brightness control or VGA?

(If there's somewhere else I should take this discussion just let me know)

**Comment by jrandiny** [comment]
Can you provide the following info
- Ubuntu version
- Exact model of your laptop (check the bottom of the laptop)
- Your original dsdt table dump
- BIOS version

**Comment by jkflying** [comment]
* Ubuntu 20.04.1 with latest mainline kernel 5.9.8
* zip attached of the dump. [dsdt.zip](https://github.com/jrandiny/yoga-slim7-ubuntu/files/5545172/dsdt.zip) Note it is of a git repo, you can check out the latest master to see what my results were after compiling and what patches I applied
```
julian@Condor:~/Documents$ sudo inxi -M
Machine:   Type: Laptop System: LENOVO product: 82A2 v: Yoga Slim 7 14ARE05 serial: --redacted-- 
           Mobo: LENOVO model: LNVNB161216 v: SDK0J40709 WIN serial: --redacted-- UEFI: LENOVO 
           v: DMCN32WW date: 07/14/2020 
```
I see there's a newer bios available from Lenovo, just a few weeks old, but I'm hesitant to apply it if the patch will suddenly be completely different, since I don't understand what I'm doing at all in the .dsl file. It mentions something changing in the S0i3.

**Comment by jrandiny** [comment]
Hmm it seems that your dsdt.dsl file is on revision 1 while mine is on revision 2. I think Lenovo update the table at some point and somehow you got the older revision

**Comment by jrandiny** [comment]
And can you verify the following patch (https://gist.github.com/jrandiny/9e585b68ac92c766c9252f4c03a51aaf) fix your compilation

**Comment by jkflying** [comment]
Confirmed, this works! Thanks for your help.

Out of curiosity, have you tried the new BIOS update yet?

**Comment by jrandiny** [comment]
I haven't tried it, this is my main machine so I'm afraid of breaking changes. I will wait until holiday before trying it

**Comment by jkflying** [comment]
FYI: firmware update works, but until you re-generate the patched firmware overrides (ie. if you boot with the old one still) your trackpad won't work.

**Comment by martin2250** [comment]
Just FYI: I tried this today and got stuck at the rev1 patch.

My System:
```
BIOS Information
        Vendor: LENOVO
        Version: DMCN36WW
        Release Date: 11/18/2020
        Address: 0xE0000
        BIOS Revision: 1.36
        Firmware Revision: 1.28
System Information
        Manufacturer: LENOVO
        Product Name: 82A2
        Version: Yoga Slim 7 14ARE05
```

The patch you've mentioned [here](https://github.com/jrandiny/yoga-slim7-ubuntu/issues/11#issuecomment-728124064) doesn't work anymore. Instead, it is sufficient to remove only the line (somewhere at line 59)
```
External (AFN7, MethodObj)    // 1 Arguments
```

Hope that saves somebody the trouble I've had.

Thanks Joshua for your work!

**Comment by jrandiny** [comment]
Hm interesting, can you send your original decompiled file?

**Comment by martin2250** [comment]
sure, here you go: 
[dsdt.dsl.gz](https://github.com/jrandiny/yoga-slim7-ubuntu/files/5997958/dsdt.dsl.gz)
