### ISSUE TITLE
ACPI decompile error

### ISSUE THREAD

**Issue by sssemil** [jrandiny/yoga-slim7-ubuntu#12]
Hi, I'm trying to enable S3, and I'm getting error messages when executing "iasl -e *.dat -d dsdt.dat" command.

Error messages - https://gist.github.com/sssemil/1577d20801acb3510845fb4ddf73ea70

Then patch also fails partially:
```
patch < ../dsdt.patch    

patching file dsdt.dsl
Reversed (or previously applied) patch detected!  Assume -R? [n] n
Apply anyway? [n] y
Hunk #1 FAILED at 1.
Hunk #2 succeeded at 18 (offset -60 lines).
Hunk #3 succeeded at 914 (offset -63 lines).
Hunk #4 succeeded at 11101 (offset -269 lines).
1 out of 4 hunks FAILED -- saving rejects to file dsdt.dsl.rej
```
dsdt.dsl.rej - https://gist.github.com/sssemil/cd01368e157f9330d48d9b00e1aa9cae

Is this normal? For reference, I'm using Lenovo Yoga Slim 7-14ARE05 with AMD Ryzen 7 4800U.

Thanks for any help!

**Comment by jrandiny** [comment]
As long as the recompilation works, it should be fine

**Comment by sssemil** [comment]
Alright, using unlocked BIOS method anyways, but thanks :)
