### ISSUE TITLE
Standby for Manjaro

### ISSUE THREAD

**Issue by rajibahmed** [jrandiny/yoga-slim7-ubuntu#16]
Hi, 

As I am using PopOS, the instruction here do not match after I have generated the acpi override. 
PopOS uses systemd-boot, not grub. So I can't edit grub config.

Seems like `kernelstub` is the tool that I should use to update the kernel params. I have not tired it yet. If it works, I will post it here.

**Comment by rajibahmed** [comment]
Somehow I am unable to figure out how to add acpi_override to `systemd-boot` :(

**Comment by rajibahmed** [comment]
This is the documentation from arch-wiki, 

### systemd-boot

Use the initrd option to load the microcode, before the initial ramdisk, as follows:

/boot/loader/entries/entry.conf
```
title   Arch Linux
linux   /vmlinuz-linux
initrd  /cpu_manufacturer-ucode.img ## this probably become acpi_override
initrd  /initramfs-linux.img
...
```

**Comment by jrandiny** [comment]
I haven't personally tested this, however adding `initrd /path/to/acpi_override` line seems to be the correct way

**Comment by rajibahmed** [comment]
I tried it with kernel 5.8.1 with the extend patch you provided on one of the issue. I added 
`initrd /boot/acpi_override` - popOs boots normally but s3 is not published. I installed windows and updated the bios. Will give it another try and update my finding here.

**Comment by rajibahmed** [comment]
Current state - 
Update bios to the latest one - `dmcn34ww`
I switched to manjaro with dual boot and have grub now.
Now when I do the acpidump the dsdt looks different and patches are unsuccessful.
So, back to square one. I don't think I have enough expertise to make a successful tweak :(

**Comment by rajibahmed** [comment]
@jrandiny if you have some spare time please take a look at this :) https://gist.github.com/rajibahmed/20e4e2a1d26ae930e2f99d3e60428c46

**Comment by jrandiny** [comment]
Can you elaborate on "patches are unsuccessful". Does it failed at the patch command, compilation, or it just wont advertise S3 after successful setup?

**Comment by rajibahmed** [comment]
It fails on this step , trying to generate AML file - 
`iasl -ve -tc dsdt.dsl`
Error I get is - 
```
Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20201217
Copyright (c) 2000 - 2020 Intel Corporation

dsdt.dsl   3071:                             AFN7 (Local0)
Error    6086 -                                ^ Not a control method, cannot invoke (AFN7 is a Untyped)

ASL Input:     dsdt.dsl -  492693 bytes   5502 keywords  14652 source lines
Hex Dump:      dsdt.hex -  535664 bytes

Compilation failed. 1 Errors, 58 Warnings, 193 Remarks
No AML files were generated due to compiler error(s)
```

**Comment by rajibahmed** [comment]
Applying this `rev1.patch` https://github.com/jrandiny/yoga-slim7-ubuntu/issues/11 seem to fix the compilation

**Comment by rajibahmed** [comment]
Applying `dsdt.patch` + `rev1.patch` then the recompilation worked - 
```
[manjaro rajib]# dmesg | grep ACPI | grep supports
[    0.413563] ACPI: (supports S0 S3 S4 S5)
```

I will try again with systemd-boot if I can make it work or not.

**Comment by jrandiny** [comment]
Hmm okay, it seems that there are some people with different revision of the table. I will put it in the instructions soon
