### ISSUE TITLE
Any help for a Windows user, change to S3 or S2 power state

### ISSUE THREAD

**Issue by walter6469** [jrandiny/yoga-slim7-ubuntu#17]
Ok I know this is a repository for ubuntu, but I just can't seem to find help anywhere and I am desperate. This is regarding the sleep modes, my slim 7 loses 20% battery over 10hrs while sleeping, I would like to reduce this and is there ANY way except for unlocking Bios, to do this? I have little knowledge about these stuff, And ya'll seem to have a patch for it without unlocking BIOS, is there something like that for Windows? Any help is much appreciated, thanks.

**Comment by jrandiny** [comment]
Hm I don't have that problem even on Windows. However if you are curious you can try to unlock your BIOS by using this tutorial https://zhuanlan.zhihu.com/p/184982689

After that, on the BIOS there should be an option to enable S3. I haven't personally try this but I have seen someone successfully done this
