### ISSUE TITLE
HDMI audio not working

### ISSUE THREAD

**Issue by sssemil** [jrandiny/yoga-slim7-ubuntu#25]
Hi,

anyone else faced the issue of HDMI audio not working at all? HDMI audio is visible and shows as plugged-in in `pavucontrol` and isn't muted. Just no sound on the other end. Tested this cable and TV with other laptop, so that's definitely not the issue.

I'm on arch with kernel 5.10.16-zen1-1-zen.

**Comment by bramboomen** [comment]
In my case, one of the HDMI channels was muted by alsa. For me the solution was to use alsamixer, F6 to the HDMI card and unmute all channels.

**Comment by jrandiny** [comment]
I have not encounter this issue on Ubuntu 20.04 kernel 5.8

**Comment by jrandiny** [comment]
Hi, due to inactivity, I will close this issues. I have tested HDMI audio on Ubuntu 20.04 running official 5.11 kernel. Feel free to open a new bug report if you still have problem on newer kernel
