### ISSUE TITLE
Unlocking bios

### ISSUE THREAD

**Issue by barhom** [jrandiny/yoga-slim7-ubuntu#3]
Looks like some people find a way to unlock the bios.

Would be cool if we can do any of this from Linux without being forced to reinstall windows.

https://www.reddit.com/r/AMDLaptops/comments/ihsoo1/backdoor_unlocked_bios_for_lenovo_slim_7_and/
https://zhuanlan.zhihu.com/p/184982689

Any ideas?

**Comment by jrandiny** [comment]
Hmm interesting, I will try to look into this when I have the time, no promises though

**Comment by sssemil** [comment]
Tried it today on my Yoga Slim 7-14ARE05 with AMD Ryzen 7 4800U, worked perfectly! Also enabled S3 in BIOS:
```
sudo dmesg | grep ACPI:\ \(
[    0.395213] ACPI: (supports S0 S3 S4 S5)

```

**Comment by barhom** [comment]
> Tried [this](https://www.reddit.com/r/AMDLaptops/comments/ihsoo1/backdoor_unlocked_bios_for_lenovo_slim_7_and/g435d0j?utm_source=share&utm_medium=web2x&context=3) today on my Yoga Slim 7-14ARE05 with AMD Ryzen 7 4800U, worked perfectly! Also enabled S3 in BIOS:
> 
> ```
> sudo dmesg | grep ACPI:\ \(
> [    0.395213] ACPI: (supports S0 S3 S4 S5)
> ```

If I only could do this from linux.
Maybe i should boot a live windows

**Comment by sssemil** [comment]
OP in that thread said that you could if you have/can make a script to operate IO ports on Linux, so, in theory, you can, I guess.

**Comment by ko-christ** [comment]
I didn't try this yet. I first upgraded Bios to `DMCN34WW` but then I could not boot in Ubuntu 20.04 so I had to enable downgrading bios version in Bios and then revert to `DMCN32WW`. Has anyone tried the latest Bios `DMCN34WW` with Ubuntu?

**Comment by sssemil** [comment]
Yep, works fine, but I installed it over new bios. Got secure boot stuff disabled too.

**Comment by rjd22** [comment]
@ko-christ @sssemil I'm sorry for asking but I hope to get my answer here since googling doesn't give me any answers.

What would be the way to flash the bios on ubuntu if you don't have Windows installed anymore? I tried checking if UEFI capsule updates are possible but it seems this is not possible with these bios versions.

**Comment by ko-christ** [comment]
@rjd22 I really don't know how to do it from Ubuntu. Why don't you burn a freedos image with rufus or similar software and boot from it?

**Comment by ko-christ** [comment]
@sssemil what kernel are you using?
This folk also didn't manage to upgrade his bios and it is because of the unsigned 5.9 and the non secure boot settings
https://forums.lenovo.com/t5/Lenovo-Yoga-Series-Notebooks/Yoga-Slim-7-BIOS-update-to-DMCN34WW-breaks-option-Secure-Boot-No/m-p/5046311?page=1#5196561

**Comment by sssemil** [comment]
I'm using Linux 5.9.8. I flashed BIOS update in windows 10 (always good to keep like 50 GB install around for cases like this).

**Comment by rjd22** [comment]
@ko-christ Is this the way you do it? I coudn't keep the Windows 10 install sadly because of the need of full disk encryption with secure boot. Dual boot doesn't work then >_>.

**Comment by sssemil** [comment]
If you have an extra SSD, you could use it to install windows and update :P

**Comment by ko-christ** [comment]
@rjd22 I have windows installed for the bios updates.
--
@sssemil That's weird because, according to the post I linked and my personal experience with the upgrade to DMCN34WW
'Unfortunately booting in the mode "Secure Boot = No" stopped working with the last BIOS version.'
ans `5.9.8` which is an unsigned kernel requires secure boot off.

**Comment by ko-christ** [comment]
While I was in `DMCN32WW` I installed a self-signed `5.9.12` kernel and then I enabled Secure Boot.
With this setup (`DMCN32WW` + Secure Boot on) I was also able to boot with my self-signed kernel as well as with the 5.4.0 Ubuntu kernel but I was not able to boot with the unsigned `5.9.12` kernel which was kind of expected.

I then crossed my fingers and installed `DMCN34WW` but unfortunately the system didn't boot with the self-signed `5.9.12` kernel. 
The system freezes with a message `Loading ramdisk` and nothing happens.
The unsigned `5.9.12` kernel was raising another error for the unsigned kernel with a message like `please load the kernel`..
I was only able to boot with the official `5.4.0` kernel but as you may already know this is useless in Yoga Slim 7 if you need HDMI.
Turning Secure Boot off with `DMCN34WW` didn't make any difference. The option to disable secure boot is still there btw.
So again, my 2nd attempt to upgrade the BIOS failed and I had to revert to `DMCN32WW`.

If anyone has a solution to install a `5.9+` kernel with `DMCN34WW` please post it.

**Comment by jrandiny** [comment]
@ko-christ  Hmm regarding the updated bios compability maybe you can create a new issue?

**Comment by ko-christ** [comment]
yeap makes sense: https://github.com/jrandiny/yoga-slim7-ubuntu/issues/14

**Comment by rradar** [comment]
@sssemil wrote:

> Tried [this](https://www.reddit.com/r/AMDLaptops/comments/ihsoo1/backdoor_unlocked_bios_for_lenovo_slim_7_and/g435d0j?utm_source=share&utm_medium=web2x&context=3) today on my Yoga Slim 7-14ARE05 with AMD Ryzen 7 4800U, worked perfectly! Also enabled S3 in BIOS:
> 
> ```
> sudo dmesg | grep ACPI:\ \(
> [    0.395213] ACPI: (supports S0 S3 S4 S5)
> ```

This looks like the best available solution to work'a'round this annoying problem. It's also the only possible that "survies" linux re-installs, kernel changes and other OS related things. Not sure however what happens doing a bios upgrade and having this unlocked/hacked bios running before?

**Comment by sssemil** [comment]
I do not plan on updating bios any time soon, since this backdoor might get removed. But my guess is that it will just get overwritten.

**Comment by esno** [comment]
@barhom I wrote https://github.com/esno/yoga-bios-unlock to unlock mine today with `DWCN32WW` on archlinux. People saying it should work as well with `DWCN34WW` but I never tried that by myself.

**Comment by barhom** [comment]
@esno you are a life saver! I was planning on installing windows and now I do not need to. Best gift ever ;)

**Comment by barhom** [comment]
So apparently I am still on, DWCN27WW.
Ill have to update to DWCN32WW first.

**Comment by esno** [comment]
typo - sry ^^ fixed that in my comment. I never had a device running `DMCN27WW` can't tell if that would working. Only seeing people talking about `DMCN32WW` and `DWCN34WW`.

**Comment by jrandiny** [comment]
Tested with `DMCN34WW`. Thanks, I will put a link to your repo on the readme

**Comment by barhom** [comment]
Have a anyone tried 
https://bladecoder.medium.com/flash-your-lenovo-ideapad-laptop-bios-from-linux-using-uefi-capsule-updates-a82e455ea29c

On the yoga slim?

**Comment by rjd22** [comment]
@barhom sadly the bios that Lenovo supplies is not an uefi bios so flashing oy works on Windows 10.

What I did was creating a Windows GO USB stick and booted the laptop from the usb.

I did this by getting the iso from Microsoft and making an Windows Go USB with Rufus. (You need a fast usb stick for this)

**Comment by rjd22** [comment]
@jrandiny Since we now have a tool that allows for unlocking bios in Linux I think this issue can be closed.
