### ISSUE TITLE
Graphics regression in 5.11.y?

### ISSUE THREAD

**Issue by EvilOlaf** [jrandiny/yoga-slim7-ubuntu#41]
Hey there,

> Note: There seems to be a regression on Kernel 5.11 (last tested with 5.11.3), please avoid using it

Using 5.11.0-22-generic with Linux Mint at the moment and everything seems to work nicely. Either it has been fixed or I did not run into the issue..whatever it may have been.

Cheers
Werner

**Comment by jrandiny** [comment]
The official 5.11 kernel have fixed the issue
