### ISSUE TITLE
Fourth option to enable S3

### ISSUE THREAD

**Issue by EvilOlaf** [jrandiny/yoga-slim7-ubuntu#42]
There is a 4th option to advertise S3 to the system which is by unlocking the [BIOS](https://github.com/esno/yoga-bios-unlock) where you then can find an option to switch from modern standby to S3 only. 

```
$  dmesg | grep ACPI:\ \(
[    0.282431] ACPI: (supports S0 S3 S4 S5)
```

Cheers
Werner

**Comment by jrandiny** [comment]
Added to readme
