### ISSUE TITLE
wifi driver for Lenovo Yoga Slim 7 Pro 14ACH5

### ISSUE THREAD

**Issue by rouckas** [jrandiny/yoga-slim7-ubuntu#43]
In case that you would like to update your notes for the recent Yoga Slim 7 Pro:
It is using a Realtek 8852 wifi chip. It doesn't work out of the box. I installed the drivers available here
https://github.com/lwfinger/rtw89
Before loading the module, I had to disable SecureBoot as explained, e.g., here
https://askubuntu.com/questions/1114867/operation-not-permitted-when-trying-to-modprobe-xpad

Bluetooth is not working at the moment.

**Comment by tudorbarascu** [comment]
@rouckas I also did this for the same laptop. Bluetooth still wasn't working.
I found it smarter to just buy an INTEL AX200NGW (optionally, you could go with a AX210NGW - for WIFI 6). Everything works perfect now as the Intel drivers are in the kernel and greatly tested.

**Comment by jrandiny** [comment]
Sadly I don't have that device so i cannot test it, but thanks for the information
