### ISSUE TITLE
LENOVO Yoga Slim 7 PRO 14-Ryzen7 16GB 512GB - 82MS001TMH

### ISSUE THREAD

**Issue by patvdleer** [jrandiny/yoga-slim7-ubuntu#50]
Please update the README, the 82MS series does NOT come with the Intel AX200 but the RTL8852AE

https://pcsupport.lenovo.com/nl/en/products/laptops-and-netbooks/yoga-series/yoga-slim-7-pro-14ach5/82ms/parts/display/compatible

you will need https://github.com/lwfinger/rtw89

**Comment by jrandiny** [comment]
Slim 7 pro is different than slim 7 mentioned in this repo. Sorry but i can't support that model
