### ISSUE TITLE
Stuck when Shutting Down System

### ISSUE THREAD

**Issue by SteveImmanuel** [jrandiny/yoga-slim7-ubuntu#58]
**Describe the bug**
I'm not really sure whether this problem is specific to my hardware or it really is a bug. Ever since upgrading my kernel to 5.13 official, I can't seem to turn off my system. After pressing power off, the system stuck on a blank screen with blinking underscore on the top left of the screen. 

**Expected behavior**
System can shutdown completely.

**Screenshots**
After waiting for a while, the screen shows the following information and then stuck indefinitely:
![image](https://user-images.githubusercontent.com/38256664/150911432-02852e64-3d4f-427a-af6e-7bc5f6d3c2c9.png)

**Version**
 - OS: Ubuntu 20.04.3 LTS
 - Kernel: 5.13 official

**Additional context**
While using the kernel 5.13, the feature to resume after suspend, sleep, closing the laptop lid and opening it up again doesn't work. I found a workaround to mitigate this problem by downgrading the kernel to 5.12.x and everything works fine there. 

Just wanted to confirm whether anyone else experience this problem too and found better fix for this problem. Thank you.

**Comment by mike-echo-oscar-whiskey** [comment]
https://bugs.launchpad.net/ubuntu/+source/linux-hwe-5.13/+bug/1958289

**Comment by SteveImmanuel** [comment]
This issue seems to have been fixed with kernel update `5.13.0-28-generic`.
