### ISSUE TITLE
S3 still not advertised

### ISSUE THREAD

**Issue by eddykaya** [jrandiny/yoga-slim7-ubuntu#6]
Hi, tried it several times, however, there is still no S3 advertised in dmesg. Can you help me? Do you need any logs or files to check?
System: Lenovo Yoga Slim 7, 4700u, Ubuntu 20.04.1, Kernel 5.9-rc7

**Comment by jrandiny** [comment]
Could you post your grub.cfg and the s3_advertise binary

**Comment by eddykaya** [comment]
there you go:

[grub_s3_bin.zip](https://github.com/jrandiny/yoga-slim7-ubuntu/files/5318010/grub_s3_bin.zip)

**Comment by jrandiny** [comment]
From your grub.cfg it seems that the entry for acpi_s3_override is not generated. From your grub default file it seems that you use `/boot/acpi_s3_override` for the `GRUB_EARLY_INITRD_LINUX_CUSTOM` entry. It should be written without the `/boot` part

**Comment by eddykaya** [comment]
Yep, that did the trick. After fixing it, I can successfully suspend. Thank you!
