### ISSUE TITLE
Suspend not working even with s3

### ISSUE THREAD

**Issue by barhom** [jrandiny/yoga-slim7-ubuntu#7]
Hey,

My ubuntu 20.04 yoga slim 7 amd4800u which I've successfully ran the patch to add s3 suspend is not suspending properly.

Often, either the screen does not turn on.
Or the screen turns on but is frozen.

The only way to recover for me is to turn the laptop completely off and boot again.

Ideas?

**Comment by jrandiny** [comment]
Can you post the result of `cat /sys/power/mem_sleep ` and `dmesg | grep ACPI:\ \(`

**Comment by barhom** [comment]
```
➜  ~ cat /sys/power/mem_sleep 
[s2idle] deep
```

and

```
➜  ~ sudo dmesg | grep ACPI:\ \(
[sudo] password for barhom: 
[    0.392648] ACPI: (supports S0 S3 S4 S5)
```

**Comment by barhom** [comment]
I had forgotten the "=deep" part of "mem_sleep_default".

I think it will work now.

Thanks!
