### ISSUE TITLE
Audio Issues

### ISSUE THREAD

**Issue by jrandiny** [jrandiny/yoga-slim7-ubuntu#9]
It seems that a software update is breaking speaker output (headphone works fine)

Current workaround:
Add `options snd-hda-intel index=1` to `/etc/modprobe.d/alsa-base.conf` (thanks @nopmop)

However the workaround broke HDMI Audio out

Edit: Hmm, it seems that the problem show up randomly
Edit2: This seems to be related https://bugs.launchpad.net/ubuntu/+source/alsa-lib/+bug/1903570
Edit3: Fix on the way https://bugs.launchpad.net/ubuntu/+source/alsa-lib/+bug/1901922

**Comment by nopmop** [comment]
@jrandiny have you tried to add two options in `/etc/modprobe.d/alsa-base.conf`? Like so:
`options snd-hda-intel id=speakers index=1`
`options snd-hda-intel id=hdmi index=0`

I have no way of testing HDMI. It should work though. Can you confirm?

**Comment by jrandiny** [comment]
Nope it doesn't work

**Comment by nopmop** [comment]
Actually, I found a way to test HDMI.
Just use one snd-hda-intel line specifying index 0, like so: `options snd-hda-intel index=0`
Then if you connect the HDMI cable, the new device will be detected but won't be selected. You have to select it manually to output to the external monitor's speakers.

**Comment by jrandiny** [comment]
The updated package have landed on proposed repo (for Focal and Groovy). For anyone needing the fix asap, you can enable the proposed repo (https://wiki.ubuntu.com/Testing/EnableProposed) and update the package `alsa-ucm-conf`, `libasound2`, and `libasound2-data` to the latest version. Or alternatively wait for the package to land to the updates repo in about a week or two

**Comment by ko-christ** [comment]
In my case, the same update that broke the dummy output sound, broke laptop's mic as well and the suggested workarounds didn't seem to fix it. Is mic working for you?
Sound in settings does not provide any option for Input Device and pavucontrol configuration marks the input profile as "Analog Stereo Duplex (unavailable)".

```
$ cat /proc/asound/modules
 0 snd_hda_intel
 1 snd_hda_intel
$ tail -1 /etc/modprobe.d/blacklist.conf 
blacklist snd_acp3x_rn
$ tail -1 /etc/modprobe.d/alsa-base.conf
options snd-hda-intel index=1
```

I have the 3 packages updated from focal-proposed.

**Comment by jrandiny** [comment]
Should be fixed in upstream
